### ISSUE TITLE
vm methods don't propagate changes to dependant methods

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#115]
```jade
label(data-bind="text: full")
button(data-bind='click: updateName') button
```
```coffee
vm = new ViewModel	
	first: (middle)-> unless middle? then 'John' else 'John ' + middle
	last: 'Doe'
	full: -> "Full name is " + @first() + ' ' + @last()
	updateName: -> @first("Boy-scout")
```
Initially label displays 'Full name is John Doe'. After clicking the btn it should change to 'Full name is John Boy-scout Doe'. But it doesn't.

**Comment by ManuelDeLeon** [comment]
You misunderstand how reactivity works. There's nothing in the function `first` that makes it reactive. For a function to be reactive it needs to use something that calls `.depend()` on a dependency. Sessions, ReactiveVars, Mongo collections, ReactiveArrays, etc. all do it for you so you rarely need to do it yourself. ViewModel properties also do it for you automatically.

In your example you have to do:

```cs
vm = new ViewModel  
    first: -> if @middle() then 'John ' + @middle() else 'John'
    middle: ''
    last: 'Doe'
    full: -> "Full name is " + @first() + ' ' + @last()
    updateName: -> @middle("Boy-scout")
```

In this case ViewModel is calling `.depend()` for you when you access `@middle()` from the function `first`.

**Comment by avalanche1** [comment]
I see. But that's a little cumbersome - adding a middleman property.
Can't methods act as reactive sources automatically? Is that hard to implement?

**Comment by ManuelDeLeon** [comment]
It's only cumbersome because the initial example is cumbersome. You don't want to be caught dead writing that on a real app.

```cs
vm = new ViewModel  
  first: 'John'
  middle: ''
  last: 'Doe'
  fullName: -> 
    mid = if @middle() then ' ' + @middle() + ' ' else ' '
    @first() + mid + @last()
```

That way `fullName` returns the right value if you update `first`, `middle`, or `last`. You don't need an update function.

> Can't methods act as reactive sources automatically?

Again, they are reactive as long as they use a reactive source. This isn't a ViewModel issue, you'll have the same problem with any other piece of Meteor if you expect to get reactivity out of non reactive objects. For example your original `first` function will not rerun inside a `Tracker.autorun`.

I recommend watching https://www.meteorcasts.net/ep/11 and then reading https://github.com/meteor/meteor/wiki/Tracker-Manual

**Comment by avalanche1** [comment]
`You don't need an update function` - then how would I update `vm.middle` by clicking the button?

**Comment by ManuelDeLeon** [comment]
The label automatically updates itself as either first, middle, or last
change.

**Comment by avalanche1** [comment]
You mean like: `$('button').click(->vm.middle("Boy-scout"))`?

**Comment by ManuelDeLeon** [comment]
Yes but you wouldn't use jQuery and chances are you don't need to create
the view model with the constructor and reference it throughout your code
(vm).

**Comment by ManuelDeLeon** [comment]
Btw, i really think you're caught up in a bad example.

**Comment by ManuelDeLeon** [comment]
Btw, i really think you're caught up in a bad example.
