### ISSUE TITLE
#each: viewmodel data context is reset when adding data to each helper

### ISSUE THREAD

**Issue by satyavh** [ManuelDeLeon/viewmodel#141]
Hi,

I found another issue with each. See my repro again, I've updated it:
https://github.com/satyavh/viewmodel-each

The issue here is that #each viewmodel's data context is reset when parent data changes.

**Comment by ManuelDeLeon** [comment]
Believe it or not it's working as "expected".

The problem is that body's crowd array is the ultimate source of truth in this app. You loop through crowd and render peopleX based on what's on crowd. When you add a person you're not updating crowd, you're updating the copy of people which personX has. When you add an entry to crowd the screen is updated based on what's in the crowd array.

Working with sub arrays and sub documents is always tricky and error prone because you have different object references going on.

To make this example work you need to update the crowd array when you add a person, and then call `crowd.changed()` because you'd be changing an array inside crowd (not crowd itself).

**Comment by satyavh** [comment]
I thanks again for your quick reply. Ok I get it. I kind of had that idea as a solution. 
I was trying to use ViewModel.share for that, but couldn't make it work instantly. That way, all viewmodels use the same data source 'of truth'. Is that a pattern that could solve this?

**Comment by ManuelDeLeon** [comment]
This isn't a case where `share` helps. As the name suggests, it's just a simple approach to sharing data between view models (a hell of a lot simpler than Redux).

The Mongo way of putting everything in one document/object is very tedious and error prone. I highly recommend you break it down into separate collections. The structure of crowd is kinda nasty so a solution would look like:
```
Person
  : _id
  : name

People
  : _id
  : someKindOfName (if any)

PeopleGroup
  : _id
  : personId
  : peopleId


Crowd
  : _id
  : someKindOfName (if any)

CrowdGroup
  : _id
  : crowdId
  : peopleGroupId
```
It's a bit harder to read but it's a LOT easier and safer to modify.

**Comment by satyavh** [comment]
Allright, thanks for the advice. Will dive into that. Enjoy your holidays!

**Comment by ManuelDeLeon** [comment]
Thx, good luck with that. btw, it could be that your real world situation is actually simpler than this :)

**Comment by satyavh** [comment]
Thanks. Actually my real world situation is more complex and I do need to have a single source of truth.  Good thing is, I solved it :-) 

For anyone interested, the trick is to have all child viewmodels change the data model in the top parent viewmodel (the ultimate source of truth). Whenever the top view model gets "an order" from a child VM to change the model (like push or remove data), the top VM fetches the states of all child VMs and constructs a new data model based on these states including the requested changes. 

It works very well. It enables to load complex nested data, manipulate it in a component-like way, and save the manipulated data :-)

**Comment by fvpDev** [comment]
Oh my gosh...I just spent hours trying to figure out what was wrong lol. Then I updated to 2.5.3.
*facepalm*
