### ISSUE TITLE
Docs - add notice re change binding

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#174]
I'd assume many ppl will try to use `change` binding as a listener for input field change.
I would add a notice that `change` event doesn't happen only after input field loses its focus. If you need to listen to input field change you should use `input` event\binding.

**Comment by ManuelDeLeon** [comment]
Are you referring to `<input {{on "change: doSomething">` or `<input {{b "change: doSomething">`?

**Comment by avalanche1** [comment]
A good question :smile: As change event and change binding are not the same but the difference is subtle, especially for noobs)
Since there is a not in the docs about jquery event (`on "change: doSomething">`), I would simply add another note that mentions `input` javascript event.

**Comment by ManuelDeLeon** [comment]
I don't know, the `{{on ` version is documented in https://viewmodel.meteor.com/docs/bindings#declaring

And the `{{b "change: doSomething"}}` version works as expected (on every keystroke).

So if the user decides to use `{{on ` I really don't see the problem in he/she getting the event's expected behavior. It's like using `keypress` and then complain that the event is fired on and on as long as the user holds the key (it's the expected result for the event!).
