### ISSUE TITLE
Docs - add info re signals

### ISSUE THREAD

**Issue by avalanche1** [ManuelDeLeon/viewmodel#178]
History.md mentions `Add signals to capture stream of events that happen outside the view models.` but I couldnt find anything on the docs.

Btw, is v3 live now? Can I use it?

**Comment by ManuelDeLeon** [comment]
v3 is ready

I haven't added signals to the documentation because I still have one more feature to add to it. That's the ability to modify the signal (event properties) that the view model receives.

For the docs I'll probably just copy the PacMan example here: https://github.com/ManuelDeLeon/viewmodel/issues/165#issuecomment-174054066

**Comment by ManuelDeLeon** [comment]
https://viewmodel.meteor.com/docs/viewmodels#signal

**Comment by fvpDev** [comment]
:+1:

**Comment by ManuelDeLeon** [comment]
Don't tell me, blog about it =)
