### ISSUE TITLE
.depend and .changed not working between parent and children !!

### ISSUE THREAD

**Issue by HatemJerbi** [ManuelDeLeon/viewmodel#182]
code Examples:
https://github.com/HatemJerbi/viewmodel.proto1

https://github.com/HatemJerbi/viewmodel.proto2

in proto1 when you click add button autorun is executed
in proto2 when you click add button autorun is not executed

**Comment by ManuelDeLeon** [comment]
I don't see any autorun, change, or depend in there!!

**Comment by HatemJerbi** [comment]
sorry my friend, my fault. im fixing the code examples.

**Comment by HatemJerbi** [comment]
code Examples:
https://github.com/HatemJerbi/viewmodel.proto1

https://github.com/HatemJerbi/viewmodel.proto2

in proto1 when you click add button autorun is executed
in proto2 when you click add button autorun is not executed

sorry for the delay in getting back to you.

**Comment by ManuelDeLeon** [comment]
That's because you're passing a value, not a reference, when you do `triggerRefreshed=triggerRefreshed`. So person creates a new property.

btw, I really hope the code you're showing is just to demo what you thought was a problem. You're much better off using parent/child/refs/shared than tossing properties by reference. Not to say you should never do it, but there usually are cleaner ways.
