### ISSUE TITLE
setTimeout in VM

### ISSUE THREAD

**Issue by daveeel** [ManuelDeLeon/viewmodel#235]
Hi @ManuelDeLeon , I'm using setTimeouts in VM components to control their start/stop trigger. However it seems that which setTimeout could be in effect is quite unpredictable. Is there anything special that VM handles setTimeout ? Or precautions to take in general in Meteor.

**Comment by ManuelDeLeon** [comment]
Not that I know. It's a general problem with an asynchronous model.

That said, every time I end up in that situation it's because I've made a mess (manually flipping switches and turning knobs) and added a bunch of unnecessary stuff to accomplish the tasks. I just take a step back and refactor the problematic parts. I always end up with a simpler architecture.

**Comment by daveeel** [comment]
Yeah, I agree, that makes sense in general. I was asking after substantial simplification to isolate the issue. Shall try attacking the issue from different angles. Thanks for feedback.
