### ISSUE TITLE
mistake in docs - broken link to reactivearray.meteor.com

### ISSUE THREAD

**Issue by fvpDev** [ManuelDeLeon/viewmodel#265]
https://viewmodel.org/docs/misc#arrays

**Comment by fvpDev** [comment]
Also, "Old Docs (v1)" link is broken.

**Comment by ManuelDeLeon** [comment]
I think I'll just remove it. That's gone with the rest of *.meteor.com and
I don't have the willingness to bring that documentation over here.

On Jul 16, 2016 6:23 PM, "Fedor Parfenov" <notifications@github.com> wrote:

https://viewmodel.org/docs/misc#arrays

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ManuelDeLeon/viewmodel/issues/265>, or mute the thread

**Comment by ManuelDeLeon** [comment]
Updated docs, will deploy later.
