### ISSUE TITLE
Removing properties from a style binding has no effect

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/viewmodel#291]
Once set up, I can only change style-attributes with ViewModel: I cannot remove them.

1. Make a ViewModel style-binding using a helper that returns an object like `{ color: red; }`
2. After loading the page, make it so that in the object returned by the helper the key `color` becomes `null` or is entirely removed
3. **The style attribute applied via binding still says `color: red`**

Repro: https://github.com/arggh/vm-style-bind-issue

**Comment by ManuelDeLeon** [comment]
fyi, I haven't forgotten about this...

**Comment by ManuelDeLeon** [comment]
Pick up viewmodel 6.3.1

btw, your repro will still "fail" because if the color is null you're updating the styles with an empty object. You have to do something like:

```js
  divStyles() {
    return { backgroundColor: this.color() };
  },
```

I can't just remove all styles and update the with the (empty) object because that opens up a whole can of worms with styles set via regular html style attributes and ones set by VM.

**Comment by arggh** [comment]
Works like a charm, thank you!

**Comment by arggh** [comment]
Also, seems that having the style binding made like this:

```
<div {{b "style: { backgroundColor: color }"}}></div>
```

still leaves the last used background color effective after `color` becomes null. Was this also expected?

**Comment by ManuelDeLeon** [comment]
Missed that one. I'll fix it when I'm back on a computer.

**Comment by ManuelDeLeon** [comment]
Pick up 6.3.2. Thanks for the heads up.
