### ISSUE TITLE
Cant understand :/

### ISSUE THREAD

**Issue by cannap** [ManuelDeLeon/viewmodel#41]
Hi i have a Collection named: Favorites 
Now every Favorite has a Button with a bind-data click event but this is not working

here is the source:
http://laravel.io/bin/zjzmv

but the Save Collection button works fine :D i think the Problem is with this 'favorites' Line 14 since the bind-data event is in the #each favorites Line: 28

Here is a screen how it should look like
![alt](https://sc-cdn.scaleengine.net/i/5862c6709e75d30df7e18da54aed7b4b.png)

e.g:
FAV 1   Checked
FAV 2 
FAV 3  Checked

and the list should look like
//Pseudo
data =  [
{ 
packageName: FAV 1
packageId: id
},
{ 
packageName: FAV 3
packageId: id
}
]

The simple thing worked for me:
http://viewmodel.meteor.com/#checkedMultipleBk but i dont know how i can get the ID in the data array 

thx i hope you can understand me^^ my english is not so good :P

**Comment by ManuelDeLeon** [comment]
This is a common pitfall. The favorites collection in favoritesList is populated from a collection. The bind is inside the each loop in favoritesList. The order of events is as follows:

- favoritesList is rendered but it doesn't have any items in favorites because the subscription isn't ready.
- favoritesList view model is bound to the elements in the template
- Nothing inside the each loop is bound (because there are no items)
- Favorites collection is populated from server
- loop is rendered for each item in the favorites collection
- Nothing else happens because favoritesList is already bound

You have to put the contents of the each loop in a separate template and then use a view model for it. If you need to access the parent view model you can do `.parent()` on the child view model.
