### ISSUE TITLE
suggestion: "readonly" binding

### ISSUE THREAD

**Issue by ethers** [ManuelDeLeon/viewmodel#56]
Hi, I really like your package!  I know it can be done via custom binding, but this is a request for supporting "readonly" binding.  (I don't have Coffeescript set up to make a PR.)  Thanks

``<input type="text" data-bind="readonly: booleanProperty">``

**Comment by ManuelDeLeon** [comment]
What exactly is your use case? ( I can't imagine it)

**Comment by ethers** [comment]
an example: if the client already has a value, it gets displayed in the input field but not user-editable.  if the client doesn't have the value, then user can specify it.  I think it is similar to when "disabled" binding might be used, except that "readonly" allows user to copy the value to their clipboard.

**Comment by ManuelDeLeon** [comment]
You can still select the text in a disabled input, but even you couldn't I
have to disagree with having an enabled input that doesn't allow the user
to change its contents. That's what labels are for.

I understand your particular case might require it, but it's not something
I think should be added for everyone.

**Comment by ethers** [comment]
Thanks, "disabled" works well and I agree it is better
(http://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht)

**Comment by ManuelDeLeon** [comment]
One thing I forgot to mention is that you can get/set the read only attribute with the "attr" binding:
```
<input type="text" data-bind="attr: { readonly: booleanProperty }">
```
To be honest (for once?) I'm still struggling to decide whether or not I should include as few bindings as possible (what ViewModel has now) or as many as possible (readonly, href, title, etc., ones that can be used with "attr").

Right now I go with as few as possible because that's what Knockout uses and this library is modeled after Knockout. But I always have a voice in the back of my head saying I should go the Rails way and include everything but the kitchen sink.

**Comment by ethers** [comment]
Thanks for pointing out the use of "attr" binding.  IMO your approach of as few bindings as possible is good: "attr" is a pretty nice balanced solution, and you've allowed more flexibility with custom bindings when really needed.
