### ISSUE TITLE
Hopeless crush on this package

### ISSUE THREAD

**Issue by chicagogrooves** [ManuelDeLeon/viewmodel#61]
Manuel, I was a knockout fan long before Meteor, and you have not only brought back my nostalgia for it, but also given me something to show the Angular "cool kids" to say _"yeah, we got that"_ :smile: 

I will deluge you with questions/issues soon enough, but first reaching out to say hello, and thanks. It's already helping me to make a huge code-negative diff in my project [here](https://github.com/chicagogrooves/meteor-package-kitchen/pull/13/files).

Any interest in supporting ES5 getter/setter syntax for properties ?

**Comment by ManuelDeLeon** [comment]
Thank you for the kind words. I'm a fan of Knockout too (although now I see ko.observable and ko.computed on screen and I can't help but think "that's just unnecessary :p )

As for ES5, I'll think about it when Meteor drops IE8 support. I have no clue what I'm going to do because I actually like using functions to set values. It allows me to chain them.

Check out this non-trivial example app I'm working on: https://github.com/ManuelDeLeon/phonebook

Thanks again,

**Comment by chicagogrooves** [comment]
Ill check that out - meanwhile - do you think an example like this [recursive tree](http://yak-stack.meteor.com/) could be done with viewmodel ?

**Comment by ManuelDeLeon** [comment]
I don't know how to answer that. It looks more like an exercise in jquery drag and drop more than anything else.
