### ISSUE TITLE
Input lag on iOS devices

### ISSUE THREAD

**Issue by ffxsam** [ManuelDeLeon/viewmodel#72]
I noticed when typing rapidly (e.g. "20000" - hitting several 0's in a row), input gets lost. This only happens on iOS devices, not desktop browsers.

http://vmlag.meteor.com

It might take a few tries to experience this, but keep trying (I'm entering numbers such as 3200, 4800, 2200, etc).

**Comment by ManuelDeLeon** [comment]
When you say "input gets lost" do you mean the app doesn't keep up with your typing or that the input goes blank?

**Comment by ffxsam** [comment]
Correct, the app doesn't keep up with typing quickly. So if I quickly type 2800, the input might have 280 instead, or 200.

**Comment by ManuelDeLeon** [comment]
Clone this repo (at v1.8.1), add it to your project, and  try again. 

In case you need help dealing with packages: https://www.meteorcasts.net/ep/3

**Comment by cheesington** [comment]
I'm having the same issue with the phonebook app using Firefox under Windows 8.1.  I can't reproduce it using Chrome, but it's pretty obvious under FF.  Just typing my name and email address into the "I'm new here" input boxes caused the behaviour.  
For what it's worth, doesn't look like the input box is ignoring the characters as much as that it's grabbing and replacing the entire text with each keystroke.  The slightest bit of lag causes the replacement text to be a character or two behind, and those new characters appear to get lost as the input contents are overwritten.

@ManuelDeLeon, I grabbed v1.8.1 of the package, and the problem is substantially less pronounced now, but still present.

**Comment by ffxsam** [comment]
I haven't had time to try 1.8.1 yet. But it definitely has to do with using the data in several fields (performance issue). If I just have a single input box bound to a DIV, it's super fast. But I have an app where I have a whole table of calculations going on, and our users reported key dropouts so it's a problem I have to address.

Will check in later..

**Comment by ManuelDeLeon** [comment]
@cheesington Please pull the latest and try again.

**Comment by cheesington** [comment]
Bingo, I pulled the latest in [master] and it seems to work!  
Tough to prove a negative, but I couldn't get it to fail in the ways that I'd tried before.  Thanks a heap!  Now I'm going to go in there and see what you did.  :)

**Comment by ManuelDeLeon** [comment]
lol, please don't... it's embarrassing ^_^

I was delaying the value updates even when it wasn't necessary.

**Comment by cheesington** [comment]
Ha ha.  Sounds like a normal day for me.  :)
Thanks for a fantastic framework.

**Comment by ManuelDeLeon** [comment]
> Thanks for a fantastic framework.

Thanks, but as I always say, don't tell me, blog about it =)

**Comment by ffxsam** [comment]
1.8.1 fixed it for me! Thanks a ton!
