### ISSUE TITLE
Directives

### ISSUE THREAD

**Issue by niallobrien** [ManuelDeLeon/viewmodel#77]
Can we possibly get an alternative syntax such as Angular or Vue.js? Thanks.

**Comment by ManuelDeLeon** [comment]
I'm actually working on it. I'll probably release it as an "almost undocumented feature" until v 2.0. I'll put it in the documentation but won't advertise it too much. Updating all examples is a pain so I'll do it when I release v2. Here's my scratch pad for 2.0: https://github.com/ManuelDeLeon/viewmodel/blob/master/vNext.md

**Comment by niallobrien** [comment]
Awesome - I dunno if you've seen some of the work I did with Vue.js? I wrapped a validation package too, so you have a validation directive which is pretty awesome.

You can see my work here:
http://www.niallobrien.me/projects/

**Comment by ManuelDeLeon** [comment]
Thanks, I'll definitely keep that pattern in mind when I add validation. I saw your introduction to Vue.js, nice job on that. 

Not related to this conversation but I think you'll find this thread interesting (given your interest in both Vue.js and ViewModel): http://viewmodelboard.meteor.com/posts/LW6vWF8StmLQ8BhF6/state

**Comment by niallobrien** [comment]
I'd also suggest that you perhaps follow their pattern for directives which closely follows the web component spec.
```
<element
  prefix-directiveId="[argument:] expression [| filters...]">
</element>
```

```
<div v-on="click : clickHandler"></div>
```
Templates are so damn easy to read that way. :)

**Comment by ManuelDeLeon** [comment]
That's the idea. I'll add a set of common events/directives/bindings like `v-click`: 

`<div v-click="clickHandler"></div>`

Also a way for you to add your own (like you can do now), and then a `v-on` for ad-hoc events.

**Comment by niallobrien** [comment]
I'd suggest just using `v-on` for all events, like Vue.js - it would be a
little more consistent.

**Comment by ManuelDeLeon** [comment]
I'm very much against that idea. `v-on=` should need to be used on rare occasions. The keyword is 'need'. Of course you can use it always if you want. ViewModel should come with the most common events out of the box (`v-event=`) and you should use `v-on=` when you're using a custom control.

The only thing that worries me is the performance. Right now I only have to query the template for a single attribute (`data-bind`). With the `v-` pattern I have to scan each template once for each binding.

**Comment by ManuelDeLeon** [comment]
Just so you know where I'm coming from...

Right now ViewModel doesn't have a `click` binding and yet it feels like there is one: `data-bind="click: doSomething"`. I want the same experience if ViewModel moves to `v-`. The feeling that `click` isn't something extraneous but a binding in its own right, like any other.

So just like you can do:

`<div v-if="show"></div>`

The natural thing is to be able to do:

`<div v-click="show"></div>`

**Comment by niallobrien** [comment]
Wouldn't v-on make more sense so? Less directives to scan for.

**Comment by ManuelDeLeon** [comment]
There aren't that many events that need to be provided out of the box. If I can't use 30 bindings because of performance, I probably won't be able to use 15 either. Hence my biggest problem with `v-`. I haven't done any performance tests so I may be blowing it out of proportion.

**Comment by niallobrien** [comment]
I highly recommend the exact same syntax as Vue.js and I doubt you'll have performance issues.

**Comment by ManuelDeLeon** [comment]
I wouldn't be so sure about that. Check out https://github.com/ManuelDeLeon/viewmodel-vue

Creating and binding 100 Templates with 100 buttons takes an average of:

ViewModel: 385.861 ms
Vue: 1306.446 ms

btw, 
I had to check for the final button `if ($("#final" + that.data).text()) {` because Vue delays the update of the screen. The effect is not apparent with 100 templates but with 1K you see the screen full of empty buttons, Vue says "I'm done", and a lot later they get their text.

**Comment by niallobrien** [comment]
Interesting. So is the performance difference the directives or the delay that's in there?

**Comment by ManuelDeLeon** [comment]
The total

**Comment by niallobrien** [comment]
Okay, so long as we have a consistent API, I'm happy.
Also, if we could get filters & validation, that'd be super awesome! :)

**Comment by ManuelDeLeon** [comment]
The future of 'v-' isn't looking too good. I've been doing some tests and
the performance of finding elements by different 'v-' attributes isn't
something I'm comfortable with. A few ms here and there add up fast when
you have a lot of templates.

**Comment by dalgard** [comment]
This conversation is interesting to me.

What got me most excited about ViewModel, when I started using it (a week ago), and still makes me sing its praise to my colleagues, is its utter simplicity – *especially* that there is only one attribute with the simplest possible syntax.

What I dislike most about Angular is the plethora of domain-specific syntaxes and names with special meaning that I need to remember.

Prefixed with `v-` or not (but when it comes to it, I'd find `vm-` much more attractive) – I would not like polluting my otherwise clean markup with a whole set of special attributes.

**Comment by niallobrien** [comment]
Clean markup? Users of any view model solution shouldn't be so precious about their markup IMO. :)
To me, if you're using custom attributes, then make them stand out so I can read my template better & quicker. Having to scan a template with the same attribute used throughout means that I then have to read the values of each attribute just to see what it's doing. When eyeballing a template's functionality, that will only slow you & me down.

**Comment by dalgard** [comment]
I don't think there's anything inherently wrong with striving for clean markup, viewmodel or not.

With that said, I also think you are making a false argument:

1. A single word (such as `data-bind=`) will always be more recognizable than a, possibly long, list of words when scanning something – like how the twenty items on your shopping list don't immediately stand out on the shelves all at once. A prefix, luckily, alleviates the issue to some extent, especially if it has between 2 and 4 characters – but I'd venture to say that what you scan for is something-related-to-the-viewmodel *in general* more than specific binding types.

2. In the large majority of cases, there will only be a single binding inside the attribute, so reading the value is a complete non-issue – in fact ...

3. ... the special syntax of the expression inside the attribute, since it differs from standard HTML syntax, makes the type of binding and property *even more* recognizable than separate attribute-value pairs. The `: ` syntax is exemplary clear, in my opinion.

I think that separating concerns is an important principle that has served the community well. And the way to apply it here is to make sure ViewModel keeps as tightly to its own domain as possible, rather than slowly leaking into the general markup.

I know I haven't used ViewModel long, but I'd hate to see it become bloated the way Angular did.

**Comment by niallobrien** [comment]
Regarding clean markup, I agree. My statement was a joke, hence the :)
IDEs do a great job of highlighting attributes. For me, custom attributes make much more sense. While Angular can be verbose, I find Vue's included directives very easy to digest & comprehend. It's also very easy to build your own.

My shopping list doesn't have syntax highlighting. I've also wrapped the Vue-validator package for Meteor, so I'm not always using just one custom attribute. Vue uses a similar syntax to this package other than that. I might explore a Flux type approach where I create a store component, every other component will get & set the data in there. Makes it easy to share data too without direct a direct dependency on each other.

**Comment by niallobrien** [comment]
However, I'm not interested in replacing Blaze with Vue.js much like the recent work by MDG to include React, so I treat Vue as a view model on top of Blaze. It's good to talk about how other projects tackle such issues and how we can build overall better packages.
