### ISSUE TITLE
[Question] Integration Tests

### ISSUE THREAD

**Issue by Codebryo** [ManuelDeLeon/viewmodel#80]
Hi Manuel,

currently trying to dive deeper into Viewmodel. Great work so far.
I wanted to do some integration tests like:
```
describe "Creating a new project", ->

  beforeEach ->
    FlowRouter.go('/')
    #Elements
    @$form         = $('#project_create_form')
    @$inputTitle   = @$form.find('input[name=title]')
    @$list         = $('#list_of_projects')
  
  afterEach ->
    @$inputTitle.val("")
  
  it "should not allow to create projects with less than 3 characters", ->
    projectName =  "gg"
    # Fill out Input
    @$inputTitle.val(projectName)
    @$form.submit()
  
    expect(@$inputTitle.next('.error').text()).toMatch("Too short!")
    expect(@$list.text()).not.toMatch(new RegExp(projectName))
```

But this does not work as apparently the binding is not triggered correctly. I know I can test the binding directly but I wanted to do it more from the user perspective. Does this make sense ?
What would be your suggested Solution on this ?
When I found that out I will be happy to make a PR to your docs about this.

**Comment by ManuelDeLeon** [comment]
You have to raise the change event =)

**Comment by ManuelDeLeon** [comment]
I previously answered from my phone so here's the detailed version. 

The thing is that when you change a value via JavaScript or JQuery, the events are not fired. It makes sense because if you set an input's value to "X", do you mean that it changed to X, the user typed X, copy/pasted a string containing X, etc.?

So in your case raise a change event after you update the input:

```
@$inputTitle.trigger 'change'
```

I don't remember exactly how JQuery and Mocha work together so you might need to delay the assertion until the next JS event cycle (setTimeout 0 ms). I'm not sure about this one so first test without it.

Let me know if you need help.

**Comment by ManuelDeLeon** [comment]
Warning: Unsolicited opinion ahead...

I don't like those kinds of integration tests because they're too artificial. You're manipulating the screen via code so there's a good chance that the application behaves differently when used by a real person. I would recommend testing your view models (your code), testing that the bindings are in place, and then performing end-to-end tests with Selenium or something similar.

Those are my 2 completely unsolicited cents... but at least they're free =)

**Comment by Codebryo** [comment]
Thanks Manuel for the answer.
It totally makes sense and I also appreciate your honest opinion very much. 
You are probably right on only testing if the binding works mostly when working with view model.

I more tried to have everything running with Velocity and Jasmin and running integration tests, unit tests all with the same system. 
Thanks for the Answer. I will close this issue for now but will post my findings and results.
