### ISSUE TITLE
Bind attribute name in vNext

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#83]
I looked through `vNext.md` and am very impressed by the way that you're examining any idea that may improve the API; as I said earlier, I think the library already has a very concise and effective way of getting things done. Much respect.

The name of the actual HTML attribute isn't that important, in my opinion, but `db="...">` could be a bit confusing.

I suggest something like `viewmodel="...">`, `vm="...">`, `bind-vm="...">`, or simply `bind="...">` – but at the same time think you should keep `data-bind="...">` for those who get uncomfortable without the `data-` prefix :)

**Comment by ManuelDeLeon** [comment]
Thanks for the compliment. I try hard to make development as painless as possible.

The goal is to be concise out of the box (less crap), so `db=` as shorthand for `data-bind=` seems fitting. `vm=` doesn't seem right because you're not declaring a view model but the bindings instead.

I plan to give the user the option to change it with one line anyway. So if you prefer `viewmodel=` or `data-bind=` you can just add `ViewModel.BindAttribute = "data-bind";` somewhere and you're good to go.

**Comment by dalgard** [comment]
`.bindAttribute` sounds good – and fair point about `vm=`. I still think `db=` is confusing, though, since it pretty ubiquitously refers to a database.

Maybe you view `data-bind` as a full name, rather than as a HTML5 data attribute with the name `bind`?

I think many will interpret the attribute's name as simply `bind`, the way it is used now. But I think omitting the `data` prefix would send a nice signal, since it would make ViewModel feel more like a native part of Meteor*.

*The same way the framework uses the `name=` attribute on `<template>` without the HTML5 `data` prefix and the way Angular doesn't care about prefixing its attributes, either
