### ISSUE TITLE
Helping out on the project

### ISSUE THREAD

**Issue by dalgard** [ManuelDeLeon/viewmodel#90]
I'm really into this project, as is apparent from my many posts (most of which are nearing a conclusion), and I would like to help out. How do you feel about pull requests?

The API of ViewModel is great and so is the documentation, especially considering that you did it on your own.

There are a few things about the code that I would consider refactoring – maybe we could collaborate on v2?

One of the things I notice in the current code is that the ViewModel class adds methods to each instance inside the constructor instead of using the prototype. Is there a particular reason for this?

Cheers!

**Comment by ManuelDeLeon** [comment]
I'd love to have a helping hand. To be honest (for once?) one of the reasons I'm looking forward to v2 is that I'll be able to rewrite the library and have the benefit of hindsight (I'm surprised the code isn't more of a mess). I'm also planning on doing optimizations like using js object keys instead of arrays and stuff like that.

I think it's better for us to work on v2 than refactor v1. Wouldn't you agree?

I really like the workflow I used for v1 in which for every feature I would create the documentation, implement it, and create the tests. Then move to another feature, rinse and repeat.

Thoughts?

> Is there a particular reason for this?

None whatsoever =p

**Comment by dalgard** [comment]
Sounds great – I'm in :)

Do you have something like a Trello board for v2?

Would you consider switching to ES6? I think it's a great fit for this package.

**Comment by ManuelDeLeon** [comment]
> Would you consider switching to ES6?

And force the ecmascript and shim packages on the users? Not a chance.

I'm open to JavaScript but I'm thinking of being selfish and go with CoffeeScript. It just makes me smile. The ugly parts of the ViewModel code are a product of doing things haphazardly, not because of CoffeeScript.

Don't have a Trello board, just the vNext document =)

I'd like to change the documentation so that it pulls information from the database instead of being a static site. You and I (as admins) would be able to add new sections using html or markdown without redeploying the app. That is easy, the hard part is that I also want to be able to add live examples like in the current documentation. So we would need a system that we can add code and run it on the fly like JSFiddle. 

That would really improve the quality of the documentation because I often don't modify it because it's a mini hassle. With that system it would be a matter of clicking an edit button on the page, make the modification, and saving it.

Is this a problem you'd be interested in working on? If you do then of course you can do the documentation site in ES6 =D

ping me at manueldeleon at gmail. We should discuss something offline.

**Comment by ManuelDeLeon** [comment]
Shoot me an email when you get a chance...

**Comment by dalgard** [comment]
First chance I get :)
